"""Golden tests: with the prototype-compatible catalog overlay, the engine must reproduce the
console prototype's results for reference scenarios.

``tests/golden/prototype_scenarios.json`` was generated by running the ORIGINAL
``counter_location.py`` functions (compute_topology / build_bom / build_ip_plan).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from sitesizer.core.catalog import Catalog
from sitesizer.core.models import SiteInput
from sitesizer.core.sizing import size_site

GOLDEN = json.loads((Path(__file__).parent / "golden" / "prototype_scenarios.json").read_text(encoding="utf-8"))
SCENARIOS = {s["id"]: s for s in GOLDEN["scenarios"]}

# Prototype UPS/OOB rows have placeholder models; compare them by role only.
ROLE_GROUPS = {"ups": "power", "oob": "power"}


def _equipment(rows: list[dict]) -> list[tuple[str, str, int]]:
    return [(r["group"], r["model"], r["qty"]) for r in rows if r["group"] not in ("ups", "oob", "reference")]


@pytest.mark.parametrize("scenario_id", list(SCENARIOS))
def test_bom_matches_prototype(scenario_id: str, compat_catalog: Catalog) -> None:
    sc = SCENARIOS[scenario_id]
    result = size_site(SiteInput.model_validate(sc["input"]), compat_catalog)
    ours = [
        (line.group, line.model, line.qty)
        for line in result.bom
        if line.group in ("ap", "wifi_switch", "access_switch", "camera_switch", "core_switch", "firewall")
    ]
    assert ours == _equipment(sc["prototype_bom"])

    proto_groups = [r["group"] for r in sc["prototype_bom"]]
    our_power = [line for line in result.bom if line.group == "power"]
    assert len(our_power) == proto_groups.count("ups") + proto_groups.count("oob")
    if "oob" in proto_groups:
        assert any(line.model == "OOB-LTE" for line in our_power)


@pytest.mark.parametrize(
    "scenario_id", [k for k, s in SCENARIOS.items() if any(r["group"] == "ups" for r in s["prototype_bom"])]
)
def test_ups_watts_match_prototype(scenario_id: str, compat_catalog: Catalog) -> None:
    sc = SCENARIOS[scenario_id]
    proto = next(r for r in sc["prototype_bom"] if r["group"] == "ups")
    proto_w = int(re.search(r"≈(\d+)", proto["reason"]).group(1))  # type: ignore[union-attr]
    result = size_site(SiteInput.model_validate(sc["input"]), compat_catalog)
    ups = next(line for line in result.bom if line.group == "power" and line.model != "OOB-LTE")
    assert f"≈{proto_w} Вт" in ups.reason
    assert round(result.power.legacy_w) == proto_w


@pytest.mark.parametrize("scenario_id", [k for k, s in SCENARIOS.items() if s["prototype_ip_plan"]])
def test_ip_plan_matches_prototype(scenario_id: str, compat_catalog: Catalog) -> None:
    sc = SCENARIOS[scenario_id]
    result = size_site(SiteInput.model_validate(sc["input"]), compat_catalog)
    assert result.ip_plan is not None
    assert len(result.ip_plan.segments) == len(sc["prototype_ip_plan"])
    for seg, row in zip(result.ip_plan.segments, sc["prototype_ip_plan"], strict=True):
        if scenario_id == "multi_group_reserve" and seg.id in ("wifi", "mgmt"):
            # Known, intentional difference: with several AP groups the AP total is the sum of
            # the reserved groups (2 + 2 = 4, matching the BoM lines); the prototype used
            # ceil(2 × 1.2) = 3 for the total. Wi-Fi hosts: 4 × 15 vs 3 × 15.
            delta = 15 if seg.id == "wifi" else 1
            assert seg.hosts == row["hosts"] + delta
            continue
        assert (seg.hosts, seg.prefix, seg.capacity) == (row["hosts"], int(row["prefix"].lstrip("/")), row["capacity"])


def test_reference_sla_row(compat_catalog: Catalog) -> None:
    sc = SCENARIOS["brief_example"]
    result = size_site(SiteInput.model_validate(sc["input"]), compat_catalog)
    ref = result.bom[-1]
    assert ref.group == "reference" and ref.qty is None
    assert "24x7" in ref.reason and "Критична" in ref.reason


def test_brief_example_exact(compat_catalog: Catalog) -> None:
    """The scenario spelled out in the brief."""
    sc = SCENARIOS["brief_example"]
    r = size_site(SiteInput.model_validate(sc["input"]), compat_catalog)
    assert r.core.count == 2 and r.core.model == "FS-1024E"
    assert r.firewall is not None and (r.firewall.model, r.firewall.count) == ("FG-120G", 2)
    assert (r.categories["wifi_switch"].model, r.categories["wifi_switch"].count) == ("FS-124G-FPOE", 1)
    assert (r.categories["access_switch"].model, r.categories["access_switch"].count) == ("FS-148F", 1)
    assert (r.categories["camera_switch"].model, r.categories["camera_switch"].count) == ("FS-148F-FPOE", 1)
    assert round(r.power.total_w) == 440
